### ISSUE TITLE
Looking for testers for our new DNS service

### ISSUE THREAD

**Issue by mitchellkrogza** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#293]
After several weeks of testing @funilrys and I have finally got our DNS based service online and functioning. 

This service is purely DNS based and deals with all domain names listed in Ultimate Hosts. 

This includes all derivatives of a domain name meaning xxx.com includes www.xxx.com and zzz.xxx.com and anythingyouchoose.xxx.com.

What does this mean?

Well your computer or home router can be configured to use our DNS as it's primary and only DNS which means all DNS lookups off your network are performed against our very extensive list of bad domains and it's updated daily.

It means Everytime you open a potentially harmful web site in your browser it will be blocked. So simple yet it's actually very effective.

We are in the final throws of testing and are now calling out to a maximum of 5 testers who are willing to put this to the test.

First 5 respondents will get the DNS address in the next few days.

**Comment by mitchellkrogza** [comment]
@elico any real world usage, a smartphone configured to use our DNS, a home router configured to use our DNS etc.

**Comment by spirillen** [comment]
hi @mitchellkrogza weird you are doing the same thing as i am on https://www.mypdns.org :) however i can see a twist.... i block a bit more than you facebook for ex is completely blocked. but i would like to get testers too, so if you like to share both wisdom and tester I'm all in for a new friendship

PS: just forked you two other repos (nginx|apache)-ultimate-bad-bot-blocker

**Comment by funilrys** [comment]
Hi @spirillen @elico, Mitch is AFK until an unknown date because of personal issues. 

I'm taking over his part until he comes back one day. 

Facebook access will be reviewed once we are done with the whitelist review (Ultimate-Hosts-Blacklist/dev-center#15)

Will try to call/contact Mitch so I can have direct access to the DNS server so that we may go live one day.

Cheers,
Nissar

**Comment by elico** [comment]
@spirillen I am trying to understand but not sure I understand who you aimed to.

I also just noticed: https://www.quad9.net/ which seems like a very series thing.
I have the feeling that the world is getting more sane from day to day towards the Internet.

**Comment by funilrys** [comment]
@elico Emailed you.

**Comment by elico** [comment]
@funilrys Tested to work as expected.
I will try to test it in the next few weeks but no promises on a dead line.

**Comment by DRSDavidSoft** [comment]
May I ask what software do you use to run your DNS Servers?
Personally I use DNSCrypt-proxy + Unbound, so I'm curious to see what other types of servers you guys use :)

@mitchellkrogza @spirillen

**Comment by mitchellkrogza** [comment]
Bind9

**Comment by spirillen** [comment]
> May I ask what software do you use to run your DNS Servers?
> Personally I use DNSCrypt-proxy + Unbound, so I'm curious to see what other types of servers you guys use :)
> 
> @mitchellkrogza @spirillen

I use a mix of several dns server/recursors

The public one is as follow from the public facing to backend

```
                                DNSDist  
                               /             \
                             /                 \
  PowerDNS Recursor   <=>    Powerdns
                                                RPZ zones and some real zones
```
Also testing on Unbound, but it still lacks RPZ support

**Comment by neptunepic** [comment]
Hi, I’d love to test the dns service. Can I get the server address?

**Comment by mitchellkrogza** [comment]
Sorry @neptunepic not at present, we need to rebuild the way the entire zone structure is built but will notify you once that gets done. @funilrys

**Comment by spirillen** [comment]
> Hi, I’d love to test the dns service. Can I get the server address?

Hi @neptunepic You're welcome to test mine at
```
IPv4:
95.216.209.53
116.203.32.67

IPv6:
2a01:4f9:c010:410e::53
2a01:4f8:1c0c:5f61::53
```

Any feedback would help both @mitchellkrogza, @funilrys and me develop it better. But please do note, mine do not block porn by default, they are all about privacy, and therefor might brake badly written sites google and facebook.

**Comment by funilrys** [comment]
.

**Comment by funilrys** [comment]
.

**Comment by funilrys** [comment]
We are now ready for another bulk of tester. Still interested @neptunepic ? Drop me an email or a message [out there](https://keybase.io/funilrys)

P.S.: If I don't answer in the next 24h it's because I have some other thing to think of out of OSS. :-) Everyone gets an answer with me. Not just necessarily in the next 24h.

**Comment by funilrys** [comment]
.

**Comment by funilrys** [comment]
Let's keep this open @stalebot. We are working on this.

**Comment by funilrys** [comment]
Definitively closing as per #590.

cc @elico @DRSDavidSoft @neptunepic
