### ISSUE TITLE
[FALSE-POSITIVE] binance.com ; api.binance.com

### ISSUE THREAD

**Issue by brbatv** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#595]
**Describe the subjects (domains)**
Please list any domains listed here which you believe are a false positive.
binance.com ; api.binance.com
**More Information**
How did you discover your web site or domain was listed here?

1. Can't visit. 
+
2. Spontaneous lookup in hosts file

Binance.com is the real address , should'nt be blacklisted

**Comment by Somebodyisnobody** [comment]
The affected lists are [/Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists](https://github.com/Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists), /Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists_optional and our phishing.database. @funilrys Why the website landed there?
Contact for ZeroDot1: https://gitlab.com/ZeroDot1/CoinBlockerLists

**Comment by Somebodyisnobody** [comment]
Note that ZeroDot1_optional has listed many more subdomains like

- chat.binance.com
- chat2.
- ftp.
- global.
- joinslack.
- kr.
- labs.
- launchpad.
- resource.
- resource2.
- sftp.
- stream.

The ZeroDot1 has listed
- pool.

**Comment by smed79** [comment]
https://zerodot1.gitlab.io/CoinBlockerLists/list.txt has more then 10.000 `binance.com` subdomains.

Unfortunately, `CoinBlockerLists` block too much and has too much false positive.
domains and subdomains are blocked even if they have nothing related with crypto mining.

@ZeroDot1 fyi.
