### ISSUE TITLE
Parsing Errors (domains.list)

### ISSUE THREAD

**Issue by ACodingGenie** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#600]
The following cannot be parsed as they are either just words or domains that end in a period. For the words I have listed the domains around them also to make them easier to search. Might be present in the other list files also.

...
aczsz.000webhostapp.com
aczvrifasi.000webhostapp.com
ad                                              # word
ad-ab-1.tagdelivery.com
ad-ace.doubleclick.net
...

asan-unes.firebaseapp.com. # Ends in period

...
bdx.superpools.online
bdyhvguiq.com
be                                          # word
be-betterpower.com
be-dramapassion.a.videoplaza.tv
...

...
bestwsxzsa30.club
beszachange.net
bet                                          # word
bet-52.com
bet-at-home.com
...

...
domainpark.sitelutions.com
domainplayersclub.com
domains                                  # word
domains.hiveon.net
domains.node.hiveon.net
...

...
fqvkntefmd.com
fqzyw7rz.micpn.com
fr                                             # word
fr-advertstream.a.videoplaza.tv
fr-advertstream.videoplaza.tv
...

...
groundtruth.com
groundzeroevent.com
group                                      # word
group-digital.slgnt.eu
...

hantansouloire.com. # Ends in period

...
imzahagents.com
imzuoqkrzrjw.com
in # word
in-appadvertising.com
in-automate.sendinblue.com
...

...
mtzenhigqg.com
mtzszlpypbxjm.com
mu # word
mu-ax-n.lemnisk.co
mu-ax-s.lemnisk.co
... 

Thanks.

**Comment by spirillen** [comment]
Hmm they are actually all valid TLD's.... and if they comes from a wildcard/RPZ list they would be valid :smile: 

there is nothing like

```python
*.ads    CNAME .
*.google    CNAME .
```

**Comment by ACodingGenie** [comment]
Oh alright. Something like a Pi-hole or a domain based adblocker can't really use these tho right since it wouldn't know what they are?

**Comment by rusty-snake** [comment]
> domains that end in a period …

… are just [FQDNs](https://en.wikipedia.org/wiki/Fully_qualified_domain_name) and can be [used for funny things](https://www.ghacks.net/2020/06/13/bypass-ads-on-youtube-and-some-paywalls-without-third-party-tools/).

> they are actually all valid TLD's.

yes, but https://github.com/Ultimate-Hosts-Blacklist/whitelist/issues/157

**Comment by spirillen** [comment]
Yep all domains do actually end with a `.` DOT`(The root domain) it just hidden in most operations and the appended by the software

**Comment by ACodingGenie** [comment]
The more you know.
