### ISSUE TITLE
[FALSE-POSITIVE] iplists.firehol.org

### ISSUE THREAD

**Issue by amastelek** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#603]
**Help us, report at the right place!**

All the issue posted here which relates to the whitelisting process will be moved into our backend. 

Therefore, please submit your issue into our backend: https://github.com/Ultimate-Hosts-Blacklist/whitelist/issues

Thanks for your time and understanding.

The Ultimate-Hosts-Blacklist team.

------------------

**Describe the subjects (domains)**
I use firehol level 1 on my aggs to stop abusive IPs   iplists.firehol.org

**More Information**
I use it to view the status of various blocklists and this is a resource.  I use ultimate as a blocklist on DNSMASQ so it blocks this resource.
Its is no threat but extremely useful.

**Have you requested removal from other sources?**
No

Please include all relevant links to your existing removals / whitelisting.

**WARNING:** Please [search in our infrastructure](https://hosts.ubuntu101.co.za/app/contents) before submitting it.

**Additional context**

:exclamation:

We understand that this can be frustrating and embarrassing for many web site owners. The first step is to remain calm. The second step is to rest assured one of our team members will address your issue as soon as possible. Please make sure you have provided as much information as possible to help speed up the process.

**Comment by Somebodyisnobody** [comment]
@funilrys why https://github.com/Ultimate-Hosts-Blacklist/firehol_level1/blob/master/domains.list is in the system? It just contains ips (and the domain iplists.firehol.org) so it's no hosts file see also https://github.com/Ultimate-Hosts-Blacklist/firehol_level1/blob/master/clean.list
