### ISSUE TITLE
[FALSE-POSITIVE] be fr and mu ccTLD included in the blocking lists

### ISSUE THREAD

**Issue by hc6pe** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#604]
**Describe the subjects (domains)**
Please list any domains listed here which you believe are a false positive.
be
fr
mu

**More Information**
How did you discover your web site or domain was listed here?
download 
wget https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists/master/domains.list or 
wget https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists_browser/master/domains.list
grep for be, fr or mu:

➜  ~ egrep ^fr$ domains.list 
fr
➜  ~ egrep ^mu$ domains.list
mu
➜  ~ egrep ^be$ domains.list
be

**Have you requested removal from other sources?**
no

**Comment by rusty-snake** [comment]
There are even more eTLDs in the list, see https://github.com/Ultimate-Hosts-Blacklist/whitelist/issues/157.
