### ISSUE TITLE
Remove abandoned list michaeltrimm/hosts-blocking

### ISSUE THREAD

**Issue by p1r473** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#609]
michaeltrimm/hosts-blocking seems abandoned, not updated for 5 years
Please consider removing.
@dnmTX https://github.com/michaeltrimm/hosts-blocking/issues/8

**Comment by dnmTX** [comment]
There are still 15000+ active domains in it(out of 27000+).
Maybe it will be better if the upstream link is removed and to be maintained internaly as what we did [here](https://github.com/Ultimate-Hosts-Blacklist/justdomains_mirror1.malwaredomains.com).
**ping** @funilrys 
Will wait for opinions on the subject before we moved further.
