### ISSUE TITLE
Difference between hosts.deny and superhosts.deny is ambiguous.

### ISSUE THREAD

**Issue by mreutman** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#610]
When reading the documentation for `hosts.deny` and `superhosts.deny` they appear to be saying the same thing in terms of functionality; this make it hard to tell which to choose for ones system.

> WHAT IS A HOSTS.DENY FILE?
> A hosts file, named hosts.deny is a plain-text file for Linux/Unix based operating systems only which blocks a list of IP addresses on the outside of your network from gaining any access to your computer. A hosts.deny file will not work on a Windows operating system.
> WHAT IS A SUPERHOSTS.DENY FILE? I've never heard of such a thing ??
> The superhosts.deny file is simply named superhosts.deny but is actually just a normal hosts.deny file which is a plain-text file for Linux/Unix based operating systems which blocks a list of IP addresses or hosts (domains) on the outside of your network from gaining any access to your computer. If you want to use this superhosts.deny file simply rename it to hosts.deny and place it in your /etc/ folder on your Linux/Unix operating system. A hosts.deny file will not work on a Windows operating system.

The only difference I was able arrive at based on looking at the size of the files was that `superhosts.deny` blocks a larger number of IPs than the `hosts.deny` does. From there though, one is left wondering if there is some downside to using `superhosts.deny` since `hosts.deny` is the implied default.

Thanks for putting this amazing project together!

**Comment by dnmTX** [comment]
@mreutman `hosts.deny` contains only IPs. On the other hand all the domains from Ultimate.Hosts... are included in `superhosts.deny` along with the IPs from `hosts.deny`,therefore is much much larger:
![Capture](https://user-images.githubusercontent.com/34774426/117931076-5a1b3a00-b2c4-11eb-9bbe-7d846aed989c.PNG)

....hope this answers your question 👍
