### ISSUE TITLE
[HOSTS] BadIPs is offline, and the lists are likely deprecated

### ISSUE THREAD

**Issue by T145** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#615]
I haven't been able to find any sources other than https://hosts.ubuntu101.co.za/badips.txt, which is just your file mirror.

https://hosts.ubuntu101.co.za/

**Comment by funilrys** [comment]
Mitch @mitchellkrogza, is behind that source. I'm not sure it's deprecated. It comes from one of his honeypots (another network) or directly from one of his other network components.

**Comment by T145** [comment]
It does seem to be up-to-date.
`last-modified: Sun, 27 Jun 2021 10:26:40 GMT`
After bulking pinging a couple IP blocks the hosts are live as well.
