### ISSUE TITLE
[HOSTS] CHEF-KOCH's Spotify list is dead

### ISSUE THREAD

**Issue by T145** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#616]
https://raw.githubusercontent.com/CHEF-KOCH/Spotify-Ad-free/master/Spotify.txt == 404

**Comment by dnmTX** [comment]
@T145 the list was removed while ago and before you continue "informing" all of us here for things that are known already,
go to https://github.com/Ultimate-Hosts-Blacklist ,scroll down to see which lists are included here first !!!!

**Comment by T145** [comment]
@dnmTX I'm looking through your README and the host is still listed.

**Comment by T145** [comment]
https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#information-data-sources-copyrights-and-credits

**Comment by dnmTX** [comment]
> @dnmTX I'm looking through your README and the host is still listed.

... and i noted this for @funilrys  at #617. Again there is a easy way to see what's included here,please follow it.

**Comment by T145** [comment]
@dnmTX What's the proper way to see what's being included in the live build? I'm just seeing a lot of dead sources in the bold listing that says "we're including these sources," and just want to bring to attention that they should be removed from the README. I can consolidate everything in #617 if that would help out more.

**Comment by dnmTX** [comment]
> and just want to bring to attention that they should be removed from the README

And you did,in #617. Thanks 👍 

> What's the proper way to see what's being included in the live build?

Go to https://github.com/Ultimate-Hosts-Blacklist ,scroll DOWN,you'll be able to see them all.

> I can consolidate everything in #617 if that would help out more.

Nope...that be it. Thanks again 👍
