### ISSUE TITLE
[DOCS] Remove dead sources from the README

### ISSUE THREAD

**Issue by T145** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#617]
- [BadIPS.com](https://www.badips.com/)
- [CHEF-KOCH's Spotify-Ad-free](https://raw.githubusercontent.com/CHEF-KOCH/Spotify-Ad-free/master/Spotify.txt)
- [DShield.org Suspicious Domain List (High)](https://www.dshield.org/feeds/suspiciousdomains_High.txt)
- [DShield.org Suspicious Domain List (Low)](https://www.dshield.org/feeds/suspiciousdomains_Low.txt)
- [DShield.org Suspicious Domain List (Medium)](https://www.dshield.org/feeds/suspiciousdomains_Medium.txt)
- [hpHosts - GRM only](https://hosts-file.net/grm.txt)
- [Hosts ADBlock](https://raw.githubusercontent.com/eladkarako/hosts.eladkarako.com/master/build/hosts_adblock.txt)
- [lightswitch05 (Daniel)'s hosts](https://raw.githubusercontent.com/lightswitch05/hosts/master/ads-and-tracking-extended.txt)

Lightswitch is now here: https://www.github.developerdan.com/hosts/

**Comment by dnmTX** [comment]
@funilrys needs to find time and go over this,but we're still in a process of refining the lists here so it's a work in progress 👍

**Comment by funilrys** [comment]
Sources that are merged into the deployed files are - from now - only the one written into the README.

Therefore, closing.
