### ISSUE TITLE
Site down: hosts.ubuntu101.co.za

### ISSUE THREAD

**Issue by sgregori** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#619]
The site https://hosts.ubuntu101.co.za/ is down for many days, is needed to change domain or use the github raw url files ?

Thanks.

**Comment by dnmTX** [comment]
**ping** @funilrys  ☝️

**Comment by dnmTX** [comment]
@sgregori are you on Windows or Linux system?

**Comment by sgregori** [comment]
I can wait, dont worry about.

I'm using it on a linux server with dnsmasq to extend the resolutions to a lot of services.

thanks
