### ISSUE TITLE
DNS servers unreachable.

### ISSUE THREAD

**Issue by ososandy** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#622]
Hi,

I have a few windows PC's in my home. I have been using a hosts file with the blacklist for many years. But disabling the DNS Client service was breaking my windows home networking between PC's. Last week I loaded into my router the two DNS addresses. 88.198.70.38 and 88.198.70.39. I could ping them. They were slower than Google 8.8.8.8 but the blacklist benefits were well worth it. I was very happy. Well done to the great work of all the contributors to this great project. But for the last two days they have stopped working. I cannot ping them and when I do I get "Pinging 88.198.70.38 with 32 bytes of data:
Reply from 88.198.69.219: Destination host unreachable." The IP address is different?? I am in Australia. What has gone wrong?
Please excuse my lack of experience to resolve this. I am sure the answer is very simple.

**Comment by dnmTX** [comment]
**ping** @funilrys or @mitchellkrogza for assist 👍

**Comment by ososandy** [comment]
Hi,

 

Sorry for the late reply.

The DNS servers are working again?

Pinging 88.198.70.38 with 32 bytes of data:

Reply from 88.198.70.38: bytes=32 time=299ms TTL=41

Reply from 88.198.70.38: bytes=32 time=297ms TTL=41

Reply from 88.198.70.38: bytes=32 time=297ms TTL=41

Reply from 88.198.70.38: bytes=32 time=298ms TTL=41

Is there something I need to do to prevent this from happening again?

Do I close the case?

 

Regards.

**Comment by dnmTX** [comment]
@ososandy looks like it got fixed so we'll close this for now. 
If there are any disturbances in the feature,feel free to reopen and thank you for the report 👍
