### ISSUE TITLE
[FEATURE] My Awesome Idea:  I need to block only ads , but allow trackers

### ISSUE THREAD

**Issue by keerthirajap** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#632]
Hi Team,

Is there any host list available to block only ads but allow tracker.

**Comment by dnmTX** [comment]
Is this a joke or something @keerthirajap? You already asked the same question in [Steven's Repo](https://github.com/StevenBlack/hosts/issues/1819),were advised what to do and decided not to proceed further cause you're super super busy.
Now you're crusading in every other blocklist repo asking for the same thing.
As such,in my eyes you're just another **TROLL** and this issue will be rendered as **INVALID** !!!!
Closing....

**Comment by spirillen** [comment]
Of curse there is, Just look into these categorized filters. https://mypdns.org/my-privacy-dns/matrix/-/tree/master/source.

I'm more curious about why you would need only to block adware, but not trackers? In my universe the trackers(spyware) is what to blacklist, so what is the use case?

**Comment by keerthirajap** [comment]
In my universe the trackers(spyware) is what to blacklist, so what is the use case? We are working on a bot. (getthit.com)

Also, URL is not accessible (https://mypdns.org/my-privacy-dns/matrix/-/tree/master/source.).  Can you please share it again.

**Comment by spirillen** [comment]
> Also, URL is not accessible (https://mypdns.org/my-privacy-dns/matrix/-/tree/master/source.). Can you please share it again.

I know, I just updated the kernel so had to reboot the server, it should be online again.

Another source I know is doing kind of the same type of classification is the squid blacklist fro the university of Toulouse: https://dsi.ut-capitole.fr/documentations/cache/squidguard_en.html however you should be prepared for a number of FP's there as it is not maintained at the same level. (I do use this list my self, in my own squid, just only for HTTP traffic)
