### ISSUE TITLE
Set of hosts to add

### ISSUE THREAD

**Issue by Wiggum127** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#633]
Throughout the years I've gathered a small set of hostnames. Mainly tracking, but also advertising or some malware/phishing. At the time I captured these, these were not (yet) included in other projects' blacklists and slipped through my setup.

I would like to contribute these to this project (or other projects), but it's not clear to me what the best approach is.

Should I log an issue to specific repositories, depending of the type/reason to block ?

**Comment by funilrys** [comment]
Hi @Wiggum127, are you still up for this ? I would love to setup a repository for you within this GitHub organization 😄

**Comment by spirillen** [comment]
> Throughout the years I've gathered a small set of hostnames. Mainly tracking, but also advertising or some malware/phishing. At the time I captured these, these were not (yet) included in other projects' blacklists and slipped through my setup.
> 
> I would like to contribute these to this project (or other projects), but it's not clear to me what the best approach is.
> 
> Should I log an issue to specific repositories, depending of the type/reason to block ?

We at mypdns would also be very happy to receive your records, we are also developing a browser [add-on](https://mypdns.org/infrastructure/mypdns-report) for future commits for allowing more people to [approve incoming](https://mypdns.org/infrastructure/mypdns-report/-/issues/65) suggestion for blacklisting, 

Feel free to have a look

**Comment by Wiggum127** [comment]
> Hi @Wiggum127, are you still up for this ? I would love to setup a repository for you within this GitHub organization 😄

I'm still up for this. I'm currently managing my list via Gitlab https://gitlab.com/Wiggum27/blockers/-/blob/master/hosts. Doing irregular updates on an ad-hoc basis. Mainly catching domains which pass through my pi-hole setup which is already blocking 2M+ domains.

Any suggestion is welcome.

**Comment by Wiggum127** [comment]
@spirillen @funilrys see my comments above.

How do we proceed from here ?

**Comment by funilrys** [comment]
Let see how people will react to that new list 😄 
Integrated: https://github.com/Ultimate-Hosts-Blacklist/Wiggum27_Blockers 

Once the `domains.list` file will be updated, it will be merged here on the next upgrade.

**Comment by spirillen** [comment]
Sorry to abuse this thrad, but @Wiggum127 why do you have all these subdomains??


adj1.thruport.com
adj10.thruport.com
adj11.thruport.com
adj12.thruport.com
adj13.thruport.com
adj14.thruport.com
adj15.thruport.com
adj16.thruport.com
adj16r1.thruport.com
adj17.thruport.com
adj18.thruport.com
adj19.thruport.com
adj2.thruport.com
adj22.thruport.com
adj23.thruport.com
adj24.thruport.com
adj25.thruport.com
adj26.thruport.com
adj27.thruport.com
adj28.thruport.com
adj29.thruport.com
adj3.thruport.com
adj30.thruport.com
adj31.thruport.com
adj32.thruport.com
adj33.thruport.com
adj34.thruport.com
adj35.thruport.com
adj36.thruport.com
adj37.thruport.com
adj38.thruport.com
adj39.thruport.com
adj4.thruport.com
adj40.thruport.com
adj41.thruport.com
adj43.thruport.com
adj44.thruport.com
adj45.thruport.com
adj46.thruport.com
adj47.thruport.com
adj48.thruport.com
adj49.thruport.com
adj5.thruport.com
adj50.thruport.com
adj51.thruport.com
adj52.thruport.com
adj53.thruport.com
adj54.thruport.com
adj55.thruport.com
adj56.thruport.com
adj6.thruport.com
adj7.thruport.com
adj8.thruport.com
adj9.thruport.com

It seems to be invalid records: https://mypdns.org/my-privacy-dns/matrix/-/issues/980713

**Comment by Wiggum127** [comment]
Years ago (2017) I started of with the block list by StevenBlack with the standard malware list + fakenews and gambling

From that snapshot I've started adding my own findings, hardening against tracking, phishing, malware etc.

I haven't done any checking of invalid entries which no longer have a DNS entry. Those were in the StevenBlack list in 2017, but have since been abandoned. I guess this is what you've found.

I'll make the necessary changes and drop subdomains from my list in my repo.

In the meantime, how do we deal with other feedback/issues on my list?

**Comment by spirillen** [comment]
> In the meantime, how do we deal with other feedback/issues on my list?

Well in the past I started out on Gitlab just like you, then they first changed the user agreement to violate your privacy, then (now) they buttered it all up with google which is 100% blacklisted on my network

I can suggest any of these methods https://mypdns.org/mypdns/support/-/wikis/home#contact or you could make up a wiggum get in touch  repo Then I send [@homer](https://mypdns.org/homer)
