### ISSUE TITLE
[FALSE-POSITIVE] (www.)ip-api.com

### ISSUE THREAD

**Issue by thomasmerz** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#637]
**Describe the subjects (domains)**
[ip-api.com](ip-api.com)
www.ip-api.com

**More Information**
Because of this blocklist entry, someone isn't able to gather ASN infos for a given IP or domain 😞 
```
# https://github.com/trimstray/the-book-of-secret-knowledge#shell-functions-toc
function getASN () {
    local _ip="$1";
    local _curl_base="curl --request GET";
    local _timeout="15";
    _asn=$($_curl_base -ks -m "$_timeout" "http://ip-api.com/line/${_ip}?fields=as");
    _state=$(echo $?);
    if [[ -z "$_ip" ]] || [[ "$_ip" == "null" ]] || [[ "$_state" -ne 0 ]]; then
        echo -en "Unsuccessful ASN gathering.\\n";
    else
        echo -en "$_ip > $_asn\\n";
    fi
}
```

**Have you requested removal from other sources?**
Yes:
https://github.com/issues?q=is%3Aopen+is%3Aissue+author%3Athomasmerz+archived%3Afalse+ip-api.com+
https://github.com/pulls?q=is%3Aopen+is%3Apr+author%3Athomasmerz+archived%3Afalse+ip-api.com+

It has been also removed from other major blocklists:
https://blocklist-tools.developerdan.com/entries/search?q=ip-api.com

**WARNING:** Please [search in our infrastructure](https://hosts.ubuntu101.co.za/app/contents) before submitting it.
<img width="1011" alt="grafik" src="https://user-images.githubusercontent.com/18568381/160143878-41d1d31f-4a54-4196-8867-3933154ecf88.png">

**Additional context**
None.

**Comment by spirillen** [comment]
This domain is used in many apps to track your were about https://mypdns.org/my-privacy-dns/matrix/-/issues/967390
