### ISSUE TITLE
[FALSE-POSITIVE] c-0001.c-msedge.net is a CNAME for tlu.dl.delivery.mp.microsoft.com

### ISSUE THREAD

**Issue by p1r473** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#643]
**Help us, report at the right place!**

All the issue posted here which relates to the whitelisting process will be moved into our backend. 

Therefore, please submit your issue into our backend: https://github.com/Ultimate-Hosts-Blacklist/whitelist/issues

Thanks for your time and understanding.

The Ultimate-Hosts-Blacklist team.

------------------

**Describe the subjects (domains)**
c-0001.c-msedge.net is a CNAME for tlu.dl.delivery.mp.microsoft.com

**More Information**
It was breaking my Windows Update

**Have you requested removal from other sources?**

Couldnt find it upstream
![image](https://user-images.githubusercontent.com/9235633/162653477-a70ee1f2-465e-416e-a600-f1a9bb5b1e3f.png)

**Comment by funilrys** [comment]
Not the case anymore. Closing.
