### ISSUE TITLE
Google translate 

### ISSUE THREAD

**Issue by trimechee** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#648]
Hello, I went to the google translate site and the writing is unreadable and is not aligned well and the translation does not work, it happens when I put the dns of Ultimate.Hosts.Blacklist last night....

https://translate.google.com/?hl=fr&tab=TT

**Comment by funilrys** [comment]
Hi @trimechee ,  sorry for the waiting time. Were you using the DNS service or the hosts file ?

**Comment by trimechee** [comment]
There is no problem,:) thank you for your help ! i use dns servic

**Comment by funilrys** [comment]
Well, then it will be fixed in the next DNS update this night. Feel free to reopen if something is missing.

**Comment by trimechee** [comment]
Great ! Thank you very much :)
