### ISSUE TITLE
Differences between IPs lists

### ISSUE THREAD

**Issue by illydone** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#650]
Hello

The recommended download link:
https://hosts.ubuntu101.co.za/ips.list

And the following link in github:
https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/blob/master/ips/ips0.list

They don't return the same list and in the first one there's 77.75.224.0/21. This subnet includes different countries /24 subnets (Saudi Arabia, UK, France, etc.) and I doubt the whole /21 subnet is a threat.

BTW, why are these lists different?

Cheers
Jim

**Comment by funilrys** [comment]
Hi @illydone , thanks for reporting. I fixed the issue in our backend server.
