### ISSUE TITLE
[FALSE-POSITIVE]  cdn2.hubspot.net

### ISSUE THREAD

**Issue by p1r473** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#652]
More Information
How did you discover your web site or domain was listed here?
This is a Content Delivery Network (CDN) that serves static images and resources for the Hubspot network
This broke the layout of this page for me: https://www.varonis.com/blog/netcat-commands

Have you requested removal from other sources?
https://github.com/TonyRL/blocklist/issues/2
https://github.com/hemiipatu/PiHoleBlocklists/issues/14
https://github.com/blocklistproject/Lists/issues/711

https://github.com/mitchellkrogza/Phishing.Database/issues/313

![image](https://user-images.githubusercontent.com/9235633/180850043-92260749-3e1b-474f-a575-cd4fef0e4add.png)

**Comment by funilrys** [comment]
Cleaned up. Closing.

Thanks for reporting @p1r473 !
