### ISSUE TITLE
[FALSE-POSITIVE] fonts.gstatic.com

### ISSUE THREAD

**Issue by smed79** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#655]
Hi,

`fonts.gstatic.com` is blocked by UHB dns servers (not blocked in the [hosts](https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#raw-file-sources) file).

- https://user-images.githubusercontent.com/1873139/190887817-c36089c3-f46e-4212-9ae9-b3cd9130d7eb.jpg

Thank you.

**Comment by funilrys** [comment]
Note: `fonts.gstatic.com` is a `CNAME` of `gstaticadssl.l.google.com.`

**Comment by funilrys** [comment]
Reopened because DNS needs to be manually reloaded.

**Comment by funilrys** [comment]
Alright, the issue is fixed. DNS Server has been reloaded with the latest datasets. 
Closing.
