### ISSUE TITLE
[FALSE-POSITIVE] *.visualstudio.com

### ISSUE THREAD

**Issue by smed79** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#656]
Hi,

`visualstudio.com` and subdomains seems to be unreachable using **UHB** dns servers.

e.g.
- `http://visualstudio.com/`
- `https://marketplace.visualstudio.com/`

Thank you.

**Comment by funilrys** [comment]
All right, the record has been whitelisted. And the DNS server has been filled with the latest dataset.

Closing.
