### ISSUE TITLE
[FALSE-POSITIVE] winaero.com

### ISSUE THREAD

**Issue by p1r473** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#666]
False positive site about PC tweaking
Cant find it upstream. Not sure why its blocked

- https://user-images.githubusercontent.com/9235633/211179617-1253cd94-12e7-4ed3-a7bb-d9a4cb83165a.png
- https://user-images.githubusercontent.com/9235633/211179623-d5b4ca55-a3cd-4914-8ca1-d00cc5ec5921.png

**Comment by Clarity1983** [comment]
@smed79, By looking at their screenshots, @p1r473 meant winaero.**com**, not winaero.**org**
While the *.org one is inactive, winaero.com is indeed blocked and it is a website about tweaking.

**Comment by p1r473** [comment]
Sorry yes winaero.com

**Comment by p1r473** [comment]
Sorry yes winaero.com @smed79

**Comment by smed79** [comment]
Please report to the appropriate upstream list. "**Wiggum27 hosts**" in this case.

- https://gitlab.com/Wiggum27/blockers/

Thank you.

**Comment by Wiggum127** [comment]
> Please report to the appropriate upstream list. @Wiggum127 "**hosts**" in this case.
> 
>     * https://gitlab.com/Wiggum27/blockers/
> 
> 
> Thank you.

Thanks for the feedback.

This was indeed a false positive. It originates back from a merge with remembertheusers.com/files/hosts-ms. At that time flagged as doing telemetry and unwanted tracking.
I have disable the entry in my hosts file.
