### ISSUE TITLE
c-0001.c-msedge.net is a CNAME for download.windowsupdate.com

### ISSUE THREAD

**Issue by p1r473** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#670]
c-0001.c-msedge.net is a CNAME for download.windowsupdate.com
false positive

**Comment by smed79** [comment]
Hi, 

to avoid duplicate and for better tracking for the same specific issue, please post in the same thread you have opened previously https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/issues/643

Thank you.

**Comment by funilrys** [comment]
Thank you for the housekeeping @smed79
