### ISSUE TITLE
[Request] Removal of Wiggum27_Blockers

### ISSUE THREAD

**Issue by smed79** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#677]
**\# Describe problem**

[Wiggum27_Blockers](https://github.com/Ultimate-Hosts-Blacklist/Wiggum27_Blockers) cause too false positive. 

**\# Describe the solution**

Remove the list from our sources.

**\# Additional context**

I have already submitted many [fb reports](https://gitlab.com/Wiggum27/blockers/-/issues) but unfortunately no response from the maintainer (@Wiggum127).

**Comment by smed79** [comment]
https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/issues/666

**Comment by Wiggum127** [comment]
Dropped the false positive from my list.

**Comment by Wiggum127** [comment]
Any feedback is checked and validated. In case there is indeed a false positive, the records gets removed. @smed79 if you claim there are so many false positives, tell me which these are and I'll validate.

There is no need to drop my hosts file from the project.

**Comment by funilrys** [comment]
What is the actuality of this? 

Can we please avoid necrobumping?

**Comment by Wiggum127** [comment]
> What is the actuality of this?
> 
> Can we please avoid necrobumping?

Not necrobumping, believe. Out of the blue there is request to drop my hosts file is reported and the request is executed an closed within hours? There are no factual reasons to remove my hosts file.

**Comment by funilrys** [comment]
I mean, this issue has been closed in 2023 and reopened 4 days ago ... 

I can't see a valid reason to drop your list - assuming you are still actively maintaining your list. 

Stay safe and healthy!

**Comment by Wiggum127** [comment]
@funilrys Still updating and curating, yes.

**Comment by smed79** [comment]
My [last message](https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/issues/677#issuecomment-2101424841) was not a request to remove the list. but just ping in case you didn't get notified about the issue as you have said in your first message.

Sorry for the noise.
