### ISSUE TITLE
hosts.ubuntu101.co.za Down again

### ISSUE THREAD

**Issue by spirillen** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#693]
Hey @mitchellkrogza I was workikng on https://github.com/blocklistproject/Lists/pull/1252 & https://github.com/mypdns/matrix/issues/624 when I would do a search for the upstream sources for `shrtm.nu` to try help.

However I'm not able to access https://hosts.ubuntu101.co.za/app/contents/ 

![image](https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/assets/44526987/cd15660e-ef19-4a72-8de3-ab5a382793fd)

If you need a little help with some load balancing, I can provide some Nginx reverse proxy with caching

**Comment by oshunluvr** [comment]
Yes, please fix this.
