### ISSUE TITLE
[FALSE-POSITIVE] rockstargames.com

### ISSUE THREAD

**Issue by alessandrorubio** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#695]
**Help us, report at the right place!**

All the issue posted here which relates to the whitelisting process will be moved into our backend. 

Therefore, please submit your issue into our backend: https://github.com/Ultimate-Hosts-Blacklist/whitelist/issues

Thanks for your time and understanding.

The Ultimate-Hosts-Blacklist team.

------------------

**Describe the subjects (domains)**
rockstargames.com 

**More Information**
If this is blocked the rockstar client cannot run making all the respective games impossible to play. Is this intended? Such address is detailed in https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/master/domains/domains2.list

**Have you requested removal from other sources?**

Please include all relevant links to your existing removals / whitelisting.

**WARNING:** Please [search in our infrastructure](https://hosts.ubuntu101.co.za/app/contents) before submitting it.

**Additional context**

:exclamation:

We understand that this can be frustrating and embarrassing for many web site owners. The first step is to remain calm. The second step is to rest assured one of our team members will address your issue as soon as possible. Please make sure you have provided as much information as possible to help speed up the process.

**Comment by spirillen** [comment]
This domain is coming from https://github.com/Ultimate-Hosts-Blacklist/Phishing.Database which could idicate there are found phishing inside the webside

**Comment by alessandrorubio** [comment]
So, if I use this DNS or hosts file from here I cant play any rockstar games (RDR2, GTA etc). Correct?

**Comment by spirillen** [comment]
I don't know, this is not what i was trying to tell you. I gave you the source of the records, upstream, so you knew where to get in touch, to figure out why it might be blacklisted. It could very well be for good reasons, even you can see it whit the naked eye.

However and as always, keep you own whitelists, then you can exclude anything you wants

**Comment by alessandrorubio** [comment]
Ok, well... I made an issue there: https://github.com/Ultimate-Hosts-Blacklist/Phishing.Database/issues/3
